### ISSUE TITLE
Console errors in nuxt?

### ISSUE THREAD

**Issue by jackcunningham** [maoberlehner/vue-lazy-hydration#140]
In nuxt (version ^2.15.7), I'm installing with 
`npm i nuxt-lazy-hydration`

Then with a super simple example like this...
```
<LazyHydrate never>
    <component />
</LazyHydrate>
```
I get the following error when running locally in dev
**[Vue warn]: Unknown custom element: <LazyHydrate> - did you register the component correctly? For recursive components, make sure to provide the "name" option.**

It works as hoped in live without the console errors, I'm seeing a 10 point improvement in lighthouse performance score but would love to get rid of the disconcerting local errors.

I don't usually have to register components in Nuxt. The readme in npm just shows the vue docs which are a little different to nuxt. Am I missing a step in the set-up, eg Is there any config needed in `nuxt.config.js`? 

Thanks!

**Comment by jackcunningham** [comment]
Would love to solve this one, is anyone else experiencing these local errors in Nuxt 2?

**Comment by deasurv** [comment]
Hey @jackcunningham 

You need to `import LazyHydrate from 'vue-lazy-hydration'` on top of the `<script>` block in every Component or Page you want and register it to `components`; then use.

```
<script>
import LazyHydrate from 'vue-lazy-hydration'

export default {
  components: {
    LazyHydrate
  }
}
</script>
```

**Comment by jackcunningham** [comment]
Thanks @deasurv 
I got that far, I didn't realise a was looking at the vue specific docs and had to create a plugin
So in `/plugins/lazy-hydration.js` I added
```
import Vue from 'vue'
import LazyHydrate from "nuxt-lazy-hydration";
Vue.use(LazyHydrate)
```
and in `nuxt.config.js` registered it with
```
  plugins: [
    ...
    { src: "~/plugins/lazy-hydration" }
  ],
  ```
and I still need to import it locally with 
```
<script>
import LazyHydrate from 'nuxt-lazy-hydration';
export default {
    components: {
        LazyHydrate
    },
    ...
```

So that's it installed but I still get the following console error
`Invalid default value for prop "req": Props with type Object/Array must use a factory function to return the default value.`

Including this solves the console errors but still working through some weird results. The content only appears after a refresh locally.
```
<LazyHydrate never :req="{}">
```

**Comment by deasurv** [comment]
@jackcunningham
I see you used `nuxt-lazy-hydration`. have not tried that because it seems is a dead project. last publish belongs 2 years ago.

anyway, for using `vue-lazy-hydration` just try to `npm i vue-lazy-hydration`, then import it in any component or page you want, register it as a component, then simply use. that's it. you don't need the whole process of making the library as Nuxt plugin!

furthermore, new warning is related to `req` prop that you are trying to pass it to `LazyHydrate`. I can't understand what is that for? could you explain? because `vue-lazy-hydration` doesn't need that prop.

**Comment by jackcunningham** [comment]
@deasurv 
This works perfectly now. As per the docs just needed to `import LazyHydrate from 'vue-lazy-hydration';` and declare the component with `components: { LazyHydrate }`. I didn't think you had to import components in nuxt but doing it solves
