### ISSUE TITLE
unknown error with `Cannot read property 'resolved' of undefined`

### ISSUE THREAD

**Issue by bluelovers** [maoberlehner/vue-lazy-hydration#24]
https://github.com/bluelovers/test-nuxt-app/tree/test/vue-lazy-hydration

1. yarn run dev
2. go http://localhost:3000/_test/plugin/vue-lazy-hydration/2
3. click link `markdownit`
4. click link `vue-lazy-hydration/2`
5. bug happen

video
[bandicam 2019-06-23 19-02-11-922.zip](https://github.com/maoberlehner/vue-lazy-hydration/files/3317755/bandicam.2019-06-23.19-02-11-922.zip)

**Comment by maoberlehner** [comment]
Thank you for taking the time to adding reproduction link and even Video 👍

I'll look into this the next couple of days!

**Comment by maoberlehner** [comment]
As a quick workaround you can add a `key` on the div:

```html
<!-- 1.vue -->
<div key="a">
  <div>{{date}}</div>
  <div>{{text}}</div>
</div>
```

```html
<!-- 2.vue -->
<div key="b">
  <div>{{date}}</div>
  <div>{{text}}</div>
</div>
```

But I'm working on a bugfix!

**Comment by OfekA** [comment]
Having this issue as well, thanks for taking the time to work on it!

**Comment by maoberlehner** [comment]
After taking a closer look I think there is not much I can do about it.
It has something to do with the fact that Vue.js tries to reuse vdom nodes when possible.
I think using keys like in my second comment is a ok workaround.
If this is something happening to you when changing routes, you can use `$route.fullPath` as key like it is recommended here: https://slides.com/chrisvfritz/vueconf-workshop-2018-03#/34
