### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jakupi1** [maoberlehner/vue-lazy-hydration#31]
Hello just found this npm package and i wanted to test but unfortunately i cant use it from strange error that it comes from LazyHydrate.js:339:31
 ```
 <LazyHydrate when-visible>
          <post-list v-if="posts && !isLoading" :posts="posts" title="Recent Posts"></post-list>
        </LazyHydrate>
```
And it gives me error **Cannot read property '0' of undefined**  the error cames from here

```
render: function render(h) {
      var tag = this.$el ? this.$el.tagName : "div";
      var child = this.$scopedSlots.default ? this.$scopedSlots.default({
        hydrated: this.hydrated
      }) : this.$slots.default[0]; // This line causes error
      var vnode = this.hydrated ? child : h(tag); // Special thanks to Rahul Kadyan for the following lines of code.
      // https://github.com/znck
```

**Comment by taraskhvyl** [comment]
Try to change your code to:
`<LazyHydrate when-visible v-if="posts && !isLoading">
         <post-list :posts="posts" title="Recent Posts"></post-list>
       </LazyHydrate>`
