### ISSUE TITLE
ssr-only mode and optimizing Vuex INITIAL_STATE [Question]

### ISSUE THREAD

**Issue by jgimness** [maoberlehner/vue-lazy-hydration#37]
For ssr-only, like the "Article" in your example, is there any recommended way to avoid serializing the state from Vuex in INITIAL_STATE, since it will never be needed/hydrated client-side?

The Vue SSR guide requires Component's serverPrefetch (similar to Nuxt's asyncData) to store data in Vuex ( https://ssr.vuejs.org/guide/data.html ).

Great library BTW, I am pushing this to a high-traffic production website soon.

**Comment by maoberlehner** [comment]
Not that I'm aware of, unfortunately.

But Evan You hinted at SSR improvements for Vue 3 which will make this easier (and hopefully this package obsolete).

Thanks!
