### ISSUE TITLE
Support for dynamic components

### ISSUE THREAD

**Issue by simplenotezy** [maoberlehner/vue-lazy-hydration#42]
Would be great if this package supported dynamic components. Currently it does not seem to work.

**Comment by maoberlehner** [comment]
1. If this is a feature request, please provide more details and a demo what you want to achieve.
2. I'm pretty sure that this works. If you think this also could be a bug, please provide an easy way to reproduce.

**Comment by simplenotezy** [comment]
I'll provide an example later. But I have compnents like this:

<component :is="someName">

And that wouldn't render

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fifciu** [comment]
@simplenotezy I had the same problem. I used `hydrateWhenVisible` function from Readme for components. It does not throw an error

**Comment by simplenotezy** [comment]
So no solution yet @Fifciu ?

**Comment by Fifciu** [comment]
As I said I've used `hydrateWhenVisible` in `components` as a workaround

**Comment by lautr** [comment]
It works for me, i had one odd case where a dynamic component would only contain another component, but after wrapping it in a div, it worked.

thats my working code -> https://pastebin.com/EDZp64XA

**Comment by simplenotezy** [comment]
Thanks - that seems to work @Fifciu
