### ISSUE TITLE
Does this work for Nuxt’s Static Generation mode? 

### ISSUE THREAD

**Issue by simonhrogers** [maoberlehner/vue-lazy-hydration#44]
I’m very sorry for the stupid question – I can’t tell if this would work as described when an app is static generated using Nuxt. 

I have an excessive number of DOM elements on my page and I want to reduce the amount of JS required on initial page load. As far as I can tell, even in Static Generation mode, Nuxt still has to render pages in a manner which would make vue-lazy-hydration beneficial. Is this incorrect? 

Guidance much appreciated

**Comment by maoberlehner** [comment]
Yes, this works perfectly fine with `nuxt generate`
