### ISSUE TITLE
possible to pass props to import wrappers?

### ISSUE THREAD

**Issue by spacedawwwg** [maoberlehner/vue-lazy-hydration#57]
Would to be possible to add an `idleTimeout` param to `hydrateWhenIdle` similar to defining a prop on the component?

**Comment by spacedawwwg** [comment]
Now I'm thinking, I'm wondering if being able to pass any of the props to the Import Wrappers might be nice 🤔 ?

**Comment by spacedawwwg** [comment]
e.g. 
```
hydrateSsrOnly(() => import(`../my-component`), { props: { triggerHydration: this.myCondition })
```
```

**Comment by maoberlehner** [comment]
The lazy hydration props for `idleTimeout` and the Intersection Observer settings are options when using import wrappers. Trigger hydration is not supported on wrappers and I have no plans of supporting it. If you need it, you can use `<LazyHydrate>`.
