### ISSUE TITLE
Nuxt.js support

### ISSUE THREAD

**Issue by siwel** [maoberlehner/vue-lazy-hydration#62]
Hey,

What version of NUXT are supported?

When using `Nuxt.js v2.13.3`, on `universal` mode with SSR, the components are still loaded on the client with JS 

Thanks,
Lewis

**Comment by maoberlehner** [comment]
Hello!

Do you mean that they are hydrated or that they are loaded?
For the later see https://github.com/maoberlehner/vue-lazy-hydration#prevent-javascript-bundle-loading

**Comment by maoberlehner** [comment]
Just checked it in a Nuxt.js v2.13.3 environment: SSR only and delayed hydration works as expected.
For info about how to prevent loading of the JS see workarounds discussed in https://github.com/vuejs/vue/issues/9847
Thx!
