### ISSUE TITLE
Low score of Cumulative Layout Shift due to weird flashing of element on hydration

### ISSUE THREAD

**Issue by simplenotezy** [maoberlehner/vue-lazy-hydration#66]
I am trying to investigate weird flashing of elements on hydration; specifically it happens to our Hero element on our page, that is set to hydrate when visible. Have a look at this example from Google Pagespeed:

![image](https://user-images.githubusercontent.com/3786627/93008134-abc2c780-f571-11ea-84bd-8b44ec203d8e.png)

It can also be seen on our website: https://beta.thejewelleryroom.com - try to hard refresh and notice the brief blinking:

![flashing hero](https://user-images.githubusercontent.com/3786627/93008259-f7c23c00-f572-11ea-8032-b10af474763b.gif)

Anybody who knows what this could cause, or could point me in some direction?

**Comment by janKollars** [comment]
I analysed the problem a little.
When the element should be hydrated (`this.hydrated` is true) the `LazyHydrate` component returns the VNode in the default slot. However, the VNode's `componentOptions.propsData` is undefined.
Later, the `propsData` is set and we enter the render function again.

**Comment by maoberlehner** [comment]
@janKollars interesting 🤔 
Thanks for taking a closer look. I'll see if I can do something about it.
Any help is appreciated!

**Comment by simplenotezy** [comment]
Thanks @janKollars! That was a good investigation. I am curious how you did it though. I wanted to replay the rendering frame-by-frame, but I haven't found a way to do this properly.

**Comment by janKollars** [comment]
For debugging I copied the project's code and created a minimal setup.
Then, I placed breakpoints in my browser's DevTools.
You might want to watch the [line](https://github.com/maoberlehner/vue-lazy-hydration/blob/a20200820be9bdc9b34ebe5d2c6d10e90f76c290/src/LazyHydrate.js#L242) where the child is returned and check its propsData.

**Comment by j0Shi82** [comment]
Stumbled over this issue as well. It seems to be related to lazy loading the hydrated components using vue-lazy-hydration's scoped slot logic. Just lazy hydrating works and there's no flicker, but as soon as I want to lazy-load the component as well... trouble.

I managed to work around the issue by letting an independent observer watch for the intersection and using it to manually trigger the hydration. It looks like this:

```vue
      <lazy-hydrate
        v-slot="{ hydrated }"
        ssr-only
        <!-- intersected is set to true by our additional observer -->
        :trigger-hydration="intersected"
      >
        <div>
          <lazy-component
            v-if="hydrated"
            <!-- props -->
          />
        </div>
      </lazy-hydrate>
```

This seems to work just fine. The chunk lazy-loads and there's no flickering. Images are however reloaded, so I'm not sure this solves the issue of @simplenotezy. But if you just want to defer rendering outside the user's initial viewport, this might be a viable workaround.

**Comment by simplenotezy** [comment]
@j0Shi82 Thanks for your reply. Funny that you just respond, I just went to this GitHub issue to bring an update, and here's your reply only 9 minutes ago.

Anyhow. I managed to get rid of the page jumping. It was related to something else than the data-prop I believe.

How I overcame the "page jumping" issue.

I load my Hero component like this:

    Hero: hydrateWhenVisible(() => import('~/components/templates/FlexibleContent/partials/Hero.vue')),

And inside my template, I would reference it like this (simplified):

    <component :data="section" :is="'Hero'" :class="'section'" />

Inside my `Hero.vue`, it would look like this:

```
	<section
		:class="{ 'with-video' : hasVideo, 'with-image' : hasImage, 'has-text-centered' : (data.type == 2), 'has-menu' : hasMenu }"
		class="hero">
```

What I had to do was to remove the `:class` from the lazyhydrated component, and instead add the class inside the component. So it would become this:

    <component :data="section" :is="'Hero'" />

And in my component:


```
	<section
		:class="{ 'with-video' : hasVideo, 'with-image' : hasImage, 'has-text-centered' : (data.type == 2), 'has-menu' : hasMenu }"
		class="section hero">
```

And now the page don't jump. So it appears to be related to `:class`/`class` being added directly to the lazy loaded component.

I still have issues with images being reloaded/flickering, and I am not yet sure how to overcome this.

**Comment by maoberlehner** [comment]
@j0Shi82 why don't you use `when-visible`?

```html
<Lazy-hydrate when-visible>
  <div>
    <lazy-component
      <!-- props -->
    />
    </div>
</lazy-hydrate>
```

**Comment by j0Shi82** [comment]
@maoberlehner Because then the lazy-loaded items "flicker" once they get hydrated. I'll try to get a minimal repro up to make sure it's nothing on my end. Turns out my solution does alleviate the flickering, but isn't able to completely solve it either. I'll try to come back with more information.

**Comment by simplenotezy** [comment]
@maoberlehner Have you had any time to look at this yet? It's quite a big issue for our Cumulative Layout Shift score.

Here's another weird example:
![lazy](https://user-images.githubusercontent.com/3786627/98009296-ac4f4000-1df5-11eb-8096-635340c2890e.gif)

The section hydration is triggered immediately like this:

    <LazyHydrate :trigger-hydration="true">

So it's pretty weird.

**Comment by j0Shi82** [comment]
I haven't been able to get a minimal repro up, but managed to find the cause of our flickering. It seems to only occur when using the LazyHydrate component with code splitting logic (in our case with `when-visible`). This example from the official docs should have the same issue:

```vue
   <LazyHydrate
      v-slot="{ hydrated }"
      when-visible
    >
      <div>
        <CommentForm
          v-if="hydrated"
          :article-id="article.id"
        />
      </div>
    </LazyHydrate>
```

Within the lazy-loaded component I inspected the state at the time of the created hook. You can clearly see that the component inside the LazyHydrate slot "disappears" completely and then gets re-rendered, leading to a noticable "flickering" on the screen, especially for large components. More than that, it can trigger a weird hydration chain:

- Component A gets hydrated, disappears
- Component B slides to the top into the viewport, gets hydrated, disappears
- Component C slides to the top into the viewport, gets hydrated, disappears

This doesn't happen all the time, but in a good number of cases all `when-visible` components can get hydrated/rendered whenever the first `when-visible` is triggered.

Because of that I switched to the `Wrappers`, which seems to work just fine for use. You also don't run into issues when not using code-splitting.

Cheers!

**Comment by simplenotezy** [comment]
Thanks for your throughout answer @j0Shi82. I also experience issues with page jumping to top once page has been hydrated (e.g. from the initially loaded HTML that is server side rendered, and to then when page hydrates using javascript, the page jumps to top). Not sure if that's related as well?

Anyhow, in regards to the use of wrappers, do you mean import wrappers? https://github.com/maoberlehner/vue-lazy-hydration#import-wrappers

**Comment by j0Shi82** [comment]
> Anyhow, in regards to the use of wrappers, do you mean import wrappers? https://github.com/maoberlehner/vue-lazy-hydration#import-wrappers

Yes

**Comment by simplenotezy** [comment]
@j0Shi82 thanks. That worked way better, we don't see flickering anymore.

**Comment by simplenotezy** [comment]
Our organic traffic has decreased 300% since october, and it has been a huge mystery to us, why this has happened all of a sudden. Upon hours of code review and investigation a very clear picture starts to be pained: **flickering of lazy hydrated sections (resulting in page jumps and CLS) causes the decrease of traffic**. Google must've changed their algorithm (and they did). They penalise much harder on CLS now than before, so this should be considered an quite important task.

![image](https://user-images.githubusercontent.com/3786627/98139656-ba1fc680-1ec4-11eb-8fc4-fdabf4b1b1a9.png)

**Comment by maoberlehner** [comment]
Thanks all for your work on this. I'd like to take a closer look at this in the next days. It would be a great help if you can create a minimal reproduction repository.

**Comment by janKollars** [comment]
I was wrong. It had nothing to do with props. Instead, I believe the problem is caused by the render function in `loadingComponentFactory`. I tried returning a vnode "copy" of the server-side-rendered element and it works.
I will create a quick pr so you can test my solution.

**Comment by simplenotezy** [comment]
Although the page-jumping does not happen when using Wrappers, I noticed that it does/can happen when switching pages.

![ezgif-6-9d0f55e99fab](https://user-images.githubusercontent.com/3786627/98653854-d5b02480-233d-11eb-8fa9-b5642be406ca.gif)

(try live example here: https://thejewelleryroom.com).

It specifically happens when loading Product pages, where I am lazy-loading an ImageSlider component like so:

    ImageSlider: hydrateWhenIdle(() => import('~/components/product/ImageSlider')),

@maoberlehner I am happy to share access to our GitHub repo for you to review, if that would be helpful.

**Comment by maoberlehner** [comment]
@simplenotezy thanks! But I highly prefer a minimal reproduction repository.

**Comment by maoberlehner** [comment]
I just published an alpha version of 2.0! https://www.npmjs.com/package/vue-lazy-hydration/v/2.0.0-alpha.0
Although I did nothing specific to fix this issue, the changes I made could potentially fix this too.
**Attention:** `ssr-only` is now `never` as in `Hydrate? Never!`.

**Comment by hecktarzuli** [comment]
@simplenotezy Web Vitals hasn't hit Web Ranking yet.
https://twitter.com/dalmaer/status/1326201817647124480

**Comment by simplenotezy** [comment]
Awesome @maoberlehner! Where's the changelog for this? Will apply version 2 and see if it fixes the CLS issue.

**Comment by simplenotezy** [comment]
@maoberlehner I have just tested out version 2, and unfortunately it still has CLS issues, where the page will jump when switching page. See this recording:

![ezgif-7-f58b8f272fa8](https://user-images.githubusercontent.com/3786627/99550170-b60ea100-29ba-11eb-810a-bcd2fe56a234.gif)

The way I load the ImageSlider that is jumping is like so:

    ImageSlider: hydrateWhenIdle(() => import('~/components/product/ImageSlider'))

If I do it without lazy hydrating, the section will not "jump".

    ImageSlider: () => import('~/components/product/ImageSlider')

**Comment by maoberlehner** [comment]
It is really hard for me to see the problem on that gif because Idk where it starts and everything happens so quickly. Would highly prefer a video, that I can pause and play on demand.

**Comment by simplenotezy** [comment]
Hey @maoberlehner - Will this suffice? https://youtu.be/uhSBueZuFTI

**Comment by maoberlehner** [comment]
Much better. Thanks!

**Comment by simplenotezy** [comment]
Great. @maoberlehner. Perhaps if there was a way to disable LazyHydration once the page has hydrated once (and any PageSpeed score test would've completed). So when going to a new page, LazyHydration is disabled, unless explicitly enabled on some components.

**Comment by maoberlehner** [comment]
This is already happening. On route changes, lazy hydrated components should behave exactly like normal async components. Not sure why this is not the case.

**Comment by maoberlehner** [comment]
Can you please make sure that the problem still exists with 2.0.0-beta.2 I released today? Thanks!

**Comment by simplenotezy** [comment]
@maoberlehner Apologies for my late response. The issue came to my attention again after discussing this matter with a colleague of mine. I just tried installing version `2.0.0-beta.2` instead of `^1.0.0-beta.12`, however, I get this error notification right away:

    render function or template not defined in component: FlexibleContent

Not sure if there are any breaking changes I need to take care of first?

This is how I load my component:

	components: {
		FlexibleContent: () => import('~/components/templates/FlexibleContent/Sections.vue')
	},

**Comment by simplenotezy** [comment]
And could we perhaps open this issue until a solution is found? I am more than happy to help out with anything you need.

**Comment by maoberlehner** [comment]
How does `Sections.vue` look like?
Does it work without lazy hydration?
https://github.com/maoberlehner/vue-lazy-hydration#upgrade-v1x-to-v2x
