### ISSUE TITLE
Slots not working with importWrappers when migrating to v2.x

### ISSUE THREAD

**Issue by kkukelka** [maoberlehner/vue-lazy-hydration#75]
Hey, we are using vue-lazy-hydration very extensively and started migrating to version 2.0.
However, when using named slots like this while the components are imported via importWrappers
```javascript
<CustomComponent>
	<template #headline>Text</template>
	<template #button>Text</template>
</CustomComponent>
//
CustomComponent: hydrateWhenIdle(() => import('@package/components/CustomComponent.vue'))
```
the content doesn't seem to get rendered.

Using it via `<LazyHydrate />` fixed the issue for us. But we would like to know why.

**Comment by maoberlehner** [comment]
Hello Kilian! Thanks for reporting this issue! I just realized that I made a mistake when I implemented the import wrappers. I'm working on it. In the meantime you can stick to v1 or use `<LazyHydrate/>`
