### ISSUE TITLE
"export 'hydrateNever' was not found in 'vue-lazy-hydration'

### ISSUE THREAD

**Issue by FilipLundby** [maoberlehner/vue-lazy-hydration#76]
I'm trying to use hydrateNever as a wrapper, but I'm getting this warning when building the project (2.0.0-beta.1): 

```
"export 'hydrateNever' was not found in 'vue-lazy-hydration'
```

This is how I import and use it: 
```
import { hydrateNever } from 'vue-lazy-hydration';
```

```
components: {
  TheLogo: hydrateNever(() => import('@/components/TheLogo.vue')),
}
```

However, using the `never` attribute works: 
```
import LazyHydrate from 'vue-lazy-hydration';
```

```
<LazyHydrate never>
  <the-logo />
</LazyHydrate>
```

**Comment by maoberlehner** [comment]
Strange, can't reproduce. Please make sure that you're actually using v2.x. Maybe delete `node_modules` and install fresh. Thanks.

**Comment by maoberlehner** [comment]
Close because of inactivity.
