### ISSUE TITLE
Doesn't work app after update to beta

### ISSUE THREAD

**Issue by SyloRei** [maoberlehner/vue-lazy-hydration#77]
I have 2 versions of my app: SSR and CSR. After updating from the alpha version to the beta version, I got a broken CSR version.

For example, my async component definition:
`Vue.component(
  'Element',
  hydrateWhenVisible(
    () => import(/* webpackChunkName: "element" */ './tile/Element.vue'),
    { observerOptions: { rootMargin: '100px' } },
  ),
);`

Before updating, all was worked.

Error in the log doesn't exist. I think my app simply doesn't hydrate.

**Comment by maoberlehner** [comment]
Please provider a minimal reproduction (e.g. CodeSandbox). Thanks!

**Comment by SyloRei** [comment]
Sorry for the bad report. Here minimal reproduction: https://codesandbox.io/s/mystifying-snyder-siesg

You can change a version of the library and see the difference.

**Comment by maoberlehner** [comment]
Can you test with the latest version beta.4 I fixed a lot of stuff.

**Comment by SyloRei** [comment]
Recent fixes have repaired it. Thank you!
